// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8HFGjl3-hmHdW2_IMDIhMZS2qOt_gwkk',
    appId: '1:159727375475:web:b07823fac983e852614606',
    messagingSenderId: '159727375475',
    projectId: 'chat-2-b5f12',
    authDomain: 'chat-2-b5f12.firebaseapp.com',
    storageBucket: 'chat-2-b5f12.appspot.com',
    measurementId: 'G-GDLM6LTSV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5qnj7D-ccamrLad3la_ytSaFQ2lUcHR0',
    appId: '1:159727375475:android:67bf884add8056a4614606',
    messagingSenderId: '159727375475',
    projectId: 'chat-2-b5f12',
    storageBucket: 'chat-2-b5f12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQO-1050nT9sImwJrmFXdfo-i8_GRlXZU',
    appId: '1:159727375475:ios:d43d2298e0895150614606',
    messagingSenderId: '159727375475',
    projectId: 'chat-2-b5f12',
    storageBucket: 'chat-2-b5f12.appspot.com',
    iosBundleId: 'com.example.chat2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQO-1050nT9sImwJrmFXdfo-i8_GRlXZU',
    appId: '1:159727375475:ios:a866dd28aee91b0f614606',
    messagingSenderId: '159727375475',
    projectId: 'chat-2-b5f12',
    storageBucket: 'chat-2-b5f12.appspot.com',
    iosBundleId: 'com.example.chat2.RunnerTests',
  );
}
